#!/usr/bin/env sh

mode="$1"
shift

queryArguments() {
    printf "Arguments: "
    read -r args
}

case "$mode" in
    "build") mvn package;;
    "format") mvn spotless:apply;;
    "dev") mvn --quiet validate exec:java -Dexec.args="$*" -DskipTests;;
    "dev:err") mvn validate exec:java -Dexec.args="$*" -DskipTests;;
    "dev:ide") queryArguments; mvn --quiet validate exec:java -Dexec.args="$args" -DskipTests;;
    *) java -jar target/advent-of-code-1.0.0.jar "$mode" "$@";;
esac
